require_relative '../lib/data_analyst.rb'
require_relative '../lib/hypothesis_test.rb'
require_relative '../lib/confidence_interval.rb'
require_relative '../lib/test_statistic.rb'
require_relative '../lib/test_statistic_helper.rb'
require_relative '../lib/summary_stats.rb'
require_relative './data.rb'
